spring.application.name=Backend Test
server.port=8081

# ================== JWT Configuration ==================
jwt.secret=giang
jwt.expiration-ms=900000
jwt.refresh-expiration-days=7
# ================== SQLite Configuration ==================
spring.datasource.url=jdbc:sqlite:database/users.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tùy chọn
spring.sql.init.mode=always

# Tắt banner nếu muốn sạch sẽ
spring.main.banner-mode=off

# ================== GraphQL Configuration ==================
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql